"""add site_failures to troubleshooting_steps

Revision ID: 0c9cb2a69737
Revises: 6ee9d2dce1b6
Create Date: 2026-03-25 22:38:52.497549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9cb2a69737'
down_revision = '6ee9d2dce1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_failures', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.drop_column('site_failures')

    # ### end Alembic commands ###
