"""add testers handlers statuses maintenance_logs status_history

Revision ID: 28b7c86f9589
Revises: 04cdbf171e0a
Create Date: 2026-03-19 08:50:53.553430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b7c86f9589'
down_revision = '04cdbf171e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('testers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tester_type', sa.String(length=20), nullable=False),
    sa.Column('plant', sa.Integer(), nullable=False),
    sa.Column('station_number', sa.Integer(), nullable=False),
    sa.Column('current_status_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['current_status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testers_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_testers_tester_type'), ['tester_type'], unique=False)

    op.create_table('handlers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('handler_type', sa.String(length=20), nullable=False),
    sa.Column('current_tester_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['current_tester_id'], ['testers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handlers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handlers_handler_type'), ['handler_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_handlers_name'), ['name'], unique=True)

    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tester_id', sa.Integer(), nullable=False),
    sa.Column('technician', sa.String(length=100), nullable=False),
    sa.Column('fault_code', sa.String(length=50), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_logs_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_logs_tester_id'), ['tester_id'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tester_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_tester_id'), ['tester_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_tester_id'))
        batch_op.drop_index(batch_op.f('ix_status_history_changed_at'))

    op.drop_table('status_history')
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_logs_tester_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_logs_start_time'))

    op.drop_table('maintenance_logs')
    with op.batch_alter_table('handlers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handlers_name'))
        batch_op.drop_index(batch_op.f('ix_handlers_handler_type'))

    op.drop_table('handlers')
    with op.batch_alter_table('testers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testers_tester_type'))
        batch_op.drop_index(batch_op.f('ix_testers_name'))

    op.drop_table('testers')
    op.drop_table('statuses')
    # ### end Alembic commands ###
