"""add jamming session type and plan field

Revision ID: 4ed187d3ff1c
Revises: a90cc315325a
Create Date: 2026-03-19 15:33:26.233556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed187d3ff1c'
down_revision = 'a90cc315325a'
branch_labels = None
depends_on = None


def upgrade():
    # Add session_type as nullable first, backfill existing rows, then add NOT NULL
    with op.batch_alter_table('troubleshooting_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('hard_bin',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    op.execute("UPDATE troubleshooting_sessions SET session_type = 'upchuck' WHERE session_type IS NULL")

    with op.batch_alter_table('troubleshooting_sessions', schema=None) as batch_op:
        batch_op.alter_column('session_type', nullable=False)

    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.drop_column('plan')

    with op.batch_alter_table('troubleshooting_sessions', schema=None) as batch_op:
        batch_op.alter_column('hard_bin',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('session_type')

    # ### end Alembic commands ###
