"""action nullable, site_number to text, add action_tags

Revision ID: 6ee9d2dce1b6
Revises: f758df5d91b2
Create Date: 2026-03-25 22:22:37.840436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee9d2dce1b6'
down_revision = 'f758df5d91b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_tags', sa.Text(), nullable=True))
        batch_op.alter_column('site_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('site_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('action_tags')

    # ### end Alembic commands ###
