"""add description to troubleshooting sessions

Revision ID: 82ad1ed14296
Revises: 4ed187d3ff1c
Create Date: 2026-03-19 15:49:43.816580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ad1ed14296'
down_revision = '4ed187d3ff1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_sessions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
