"""add device fields to testers and failure observation to steps

Revision ID: a90cc315325a
Revises: b2e2655074df
Create Date: 2026-03-19 12:11:46.279710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90cc315325a'
down_revision = 'b2e2655074df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_device_customer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_device_part_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_device_lot_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hb_observed', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sb_observed', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('failure_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('measured_value', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('upper_limit', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('lower_limit', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.drop_column('lower_limit')
        batch_op.drop_column('upper_limit')
        batch_op.drop_column('measured_value')
        batch_op.drop_column('failure_description')
        batch_op.drop_column('sb_observed')
        batch_op.drop_column('hb_observed')
        batch_op.drop_column('pin_number')

    with op.batch_alter_table('testers', schema=None) as batch_op:
        batch_op.drop_column('current_device_lot_number')
        batch_op.drop_column('current_device_part_number')
        batch_op.drop_column('current_device_customer')

    # ### end Alembic commands ###
