"""add troubleshooting sessions and steps

Revision ID: b2e2655074df
Revises: 28b7c86f9589
Create Date: 2026-03-19 11:07:08.509584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e2655074df'
down_revision = '28b7c86f9589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('troubleshooting_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tester_id', sa.Integer(), nullable=False),
    sa.Column('hard_bin', sa.String(length=10), nullable=False),
    sa.Column('technician', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('troubleshooting_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_troubleshooting_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_troubleshooting_sessions_tester_id'), ['tester_id'], unique=False)

    op.create_table('troubleshooting_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['troubleshooting_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_troubleshooting_steps_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_troubleshooting_steps_session_id'))

    op.drop_table('troubleshooting_steps')
    with op.batch_alter_table('troubleshooting_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_troubleshooting_sessions_tester_id'))
        batch_op.drop_index(batch_op.f('ix_troubleshooting_sessions_started_at'))

    op.drop_table('troubleshooting_sessions')
    # ### end Alembic commands ###
