"""add site_count and site_number to troubleshooting_steps

Revision ID: f758df5d91b2
Revises: 82ad1ed14296
Create Date: 2026-03-25 20:47:42.033340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f758df5d91b2'
down_revision = '82ad1ed14296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('site_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('troubleshooting_steps', schema=None) as batch_op:
        batch_op.drop_column('site_number')
        batch_op.drop_column('site_count')

    # ### end Alembic commands ###
